-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 22:32:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema garantias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `garantias` ;

-- -----------------------------------------------------
-- Schema garantias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garantias` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `garantias` ;

-- -----------------------------------------------------
-- Table `garantias`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`propietario` (
  `id_propietario` INT NOT NULL,
  `nombre` VARCHAR(55) NULL,
  `dni` VARCHAR(55) NULL,
  PRIMARY KEY (`id_propietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garantias`.`garantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`garantia` (
  `DTYPE` VARCHAR(31) NOT NULL,
  `id_garantia` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `tipoGarantia` VARCHAR(55) NULL,
  `fechaDeAlta` DATE NULL,
  `precio` FLOAT NULL,
  `factor` INT NULL,
  `vigente` TINYINT NULL,
  PRIMARY KEY (`id_garantia`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `garantias`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_producto_idx` ON `garantias`.`garantia` (`id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `garantias`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`producto` (
  `DTYPE` VARCHAR(31) NOT NULL,
  `id_producto` INT NOT NULL,
  `id_propietario` INT NOT NULL,
  `modelo` VARCHAR(55) NULL,
  `factorDeImportancia` INT NULL,
  `codigo` INT NULL,
  `id_garantia` INT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `id_propietario`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `garantias`.`propietario` (`id_propietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_garantia `
    FOREIGN KEY (`id_garantia`)
    REFERENCES `garantias`.`garantia` (`id_garantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT
KEY_BLOCK_SIZE = 1;

CREATE INDEX `id_propietario_idx` ON `garantias`.`producto` (`id_propietario` ASC) VISIBLE;

CREATE INDEX `id_garantia _idx` ON `garantias`.`producto` (`id_garantia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `garantias`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`tarjeta` (
  `id_tarjeta` INT NOT NULL,
  `nombre` VARCHAR(55) NULL,
  `numero` INT NULL,
  `codigoSeguridad` INT NULL,
  `fechaDeVencimiento` DATE NULL,
  PRIMARY KEY (`id_tarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garantias`.`mercadoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`mercadoPago` (
  `id_mercadoPago` INT NOT NULL,
  `usuario` VARCHAR(55) NULL,
  `dni` VARCHAR(55) NULL,
  PRIMARY KEY (`id_mercadoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garantias`.`ordenDeCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`ordenDeCompra` (
  `id_ordenDeCompra` INT NOT NULL,
  `id_garantia` INT NOT NULL,
  `id_tarjeta` INT NOT NULL,
  `id_mercadoPago` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_ordenDeCompra`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `garantias`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_garantia`
    FOREIGN KEY (`id_garantia`)
    REFERENCES `garantias`.`garantia` (`id_garantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tarjeta`
    FOREIGN KEY (`id_tarjeta`)
    REFERENCES `garantias`.`tarjeta` (`id_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mercadoPago`
    FOREIGN KEY (`id_mercadoPago`)
    REFERENCES `garantias`.`mercadoPago` (`id_mercadoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_producto_idx` ON `garantias`.`ordenDeCompra` (`id_producto` ASC) VISIBLE;

CREATE INDEX `id_garantia_idx` ON `garantias`.`ordenDeCompra` (`id_garantia` ASC) VISIBLE;

CREATE INDEX `id_tarjeta_idx` ON `garantias`.`ordenDeCompra` (`id_tarjeta` ASC) VISIBLE;

CREATE INDEX `id_mercadoPago_idx` ON `garantias`.`ordenDeCompra` (`id_mercadoPago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `garantias`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garantias`.`servicio` (
  `id_servicio` INT NOT NULL,
  `motivo` VARCHAR(55) NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_servicio`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `garantias`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_producto_idx` ON `garantias`.`servicio` (`id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
